name: Release

permissions:
  contents: write
  pull-requests: write

on:
  push:
    branches: [main]

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: pnpm/action-setup@v4
        with:
          version: 9
          run_install: false

      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: pnpm

      - run: pnpm install
      - run: pnpm run build

      # ZC TODO: Enable this step after proper library setup
      #
      # - name: Get release version
      #   run: |
      #     pnpm changeset status --output=release.json
      #     echo "NEW_VERSION=$(jq -r '.releases[0].newVersion' release.json)" >> "$GITHUB_ENV"
      #     rm release.json

      # - name: Create Release PR
      #   uses: changesets/action@v1
      #   with:
      #     publish: pnpm changeset publish
      #     title: Release v${{ env.NEW_VERSION }}
      #     commit: 'chore(release): v${{ env.NEW_VERSION }}'
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #     NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
